feat: add fcm notification module
credebl/mediator-agent pull request #3
Opened 2024-01-11 12:39 UTC by KulkarniShashank

### What ###
Added Firebase Cloud Messaging (FCM) notification module with an initial API.

### Why ###
FCM is a reliable and widely-used solution for delivering push notifications on both Android and iOS platforms.

### How ###
1. **FCM Integration:**
   - Implemented FCM into the existing project structure to facilitate push notification delivery.
   - Set up necessary configurations and dependencies to enable communication with the FCM server.

2. **API Implementation:**
   - Added an initial API for sending push notifications from the server to the FCM service.
   - The API includes endpoints for specifying the target deviceCode(s), message content, and other relevant parameters.

2024-01-12 09:39 UTC, sairanjit requested changes

2024-01-12 09:39 UTC, sairanjit commented on src/push-notifications/fcm/services/PushNotificationsFcmService.ts
> +  public async processNotification(message: NotificationMessage) {
I think this method should be private

2024-01-12 12:20 UTC, sairanjit approved these changes
LGTM

2024-01-17 07:26 UTC, ankita-p17 approved these changes

2024-02-06 06:43 UTC, sairanjit approved these changes

2024-02-19 14:43 UTC, merged